name: Run E2E tests

on:
  pull_request:
    paths:
      - 'api-solid/**'

jobs:
  run-e2e-tests:
    name: Run E2E tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api-solid

    services:
      database-pg:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Migrate database schemas
        run: bunx prisma migrate deploy

      - name: Run E2E tests
        run: bun run "test:e2e"
        env:
          DATABASE_URL: 'postgresql://docker:docker@localhost:5432/apisolid?schema=public'
          JWT_SECRET: 'something-super-super-secret-here'
