name: Run unit tests

on:
  push:
    branches:
      - main
    paths:
      - 'challenges/challenge-03/**'

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './challenges/challenge-03'

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: install dependencies
        run: bun install

      - name: run unit tests
        run: bun run test
